// ==UserScript==
// @name         Bypass V1.3
// @namespace    devix7 workspace
// @author       devix7
// @version      10.3
// @description  Wave-lite key bypass V1.3
// @match        https://linkvertise.com/1200269/wave-key-1?o=sharing*
// @match        https://linkvertise.com/1200269/wave-key-2?o=sharing*
// @match        https://linkvertise.com/1200269/wave-key-3?o=sharing*
// @match        https://loot-link.com/s?a71a5892
// @match        https://lootdest.com/s?da8a5a9c
// @match        https://lootdest.com/s?15e1e695
// @match        https://key.getwave.gg/freemium-tasks*
// @grant        none
// ==/UserScript==

(() => {'use strict';const __jsfunc1__=()=>{const __jsvar1__=document.createElement('link');__jsvar1__.href='https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap';__jsvar1__.rel='stylesheet';document.head.appendChild(__jsvar1__);};__jsfunc1__();const __jsvar2__=[{__jsvar1__:'https://linkvertise.com/1200269/wave-key-1?o=sharing',__jsvar2__:'https://key.getwave.gg/freemium-tasks?a'},{__jsvar1__:'https://linkvertise.com/1200269/wave-key-2?o=sharing',__jsvar2__:'https://key.getwave.gg/freemium-tasks?c'},{__jsvar1__:'https://linkvertise.com/1200269/wave-key-3?o=sharing',__jsvar2__:'https://key.getwave.gg/freemium-tasks?b'},{__jsvar1__:'https://loot-link.com/s?a71a5892',__jsvar2__:'https://key.getwave.gg/freemium-tasks?d'},{__jsvar1__:'https://lootdest.com/s?da8a5a9c',__jsvar2__:'https://key.getwave.gg/freemium-tasks?e'},{__jsvar1__:'https://lootdest.com/s?15e1e695',__jsvar2__:'https://key.getwave.gg/freemium-tasks?f'}];const __jsfunc2__=(__jsarg1__,__jsarg2__)=>{console.log(`Redirecting from ${__jsarg1__} to ${__jsarg2__}`);};const __jsfunc3__=(__jsarg1__)=>{__jsfunc2__(window.location.href,__jsarg1__);setTimeout(()=>{window.location.href=__jsarg1__;},10500);};const __jsfunc4__=(__jsarg1__)=>{for(let __jsvar3__ of __jsvar2__){if(__jsarg1__.startsWith(__jsvar3__.__jsvar1__)){return __jsvar3__;}}return null;};const __jsvar4__=window.location.href;const __jsvar5__=__jsfunc4__(__jsvar4__);const __jsfunc5__=(__jsarg1__)=>{const __jsvar6__=document.createElement('div');__jsvar6__.style.position='fixed';__jsvar6__.style.top='10px';__jsvar6__.style.right='10px';__jsvar6__.style.padding='15px 50px';__jsvar6__.style.background='rgba(0,0,0,0.7)';__jsvar6__.style.borderRadius='16px';__jsvar6__.style.boxShadow='0 4px 30px rgba(0,0,0,0.1)';__jsvar6__.style.backdropFilter='blur(6.7px)';__jsvar6__.style.webkitBackdropFilter='blur(6.7px)';__jsvar6__.style.color='#fff';__jsvar6__.style.fontSize='16px';__jsvar6__.style.fontFamily='Roboto,Arial,sans-serif';__jsvar6__.style.zIndex='1000';__jsvar6__.style.textAlign='center';__jsvar6__.innerHTML=`<strong style="font-size: 20px;">Bypass v1.3</strong><br><span style="font-size: 14px;">Status: ${__jsarg1__}</span><br><span style="font-size: 12px;">made by devix7</span>`;document.body.appendChild(__jsvar6__);};if(__jsvar5__){__jsfunc5__('Bypassing, please wait...');__jsfunc3__(__jsvar5__.__jsvar2__);}else if(window.location.href.includes('https://key.getwave.gg/freemium-tasks')){__jsfunc5__('Next step in progress, please wait...');setTimeout(()=>{__jsfunc6__();},3000);}else{__jsfunc5__('No match found');}const __jsfunc6__=()=>{const __jsvar7__=document.querySelector('h1.cursor-pointer.text-3xl.max-w-3xl.mx-auto.text-center.font-semibold,a.button.relative.inline-flex.items-center.justify-center');if(__jsvar7__){__jsvar7__.click();}else{setTimeout(__jsfunc6__,2000);}}})();
